"""create table birds

Revision ID: 724a7eab07be
Revises: 4d49c064aa11
Create Date: 2023-11-21 13:30:20.272827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '724a7eab07be'
down_revision = '4d49c064aa11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('birds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('species', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('birds')
    # ### end Alembic commands ###
